name: Database Sync - Tuesday

on:
  workflow_dispatch: # adding the workflow_dispatch so it can be triggered manually
  # schedule:
  #   - cron: '0 5 * * 2'

jobs:
  qc-btms:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.DEVOPS_SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.BASTION_KNOWN_HOSTS }}
          if_key_exists: replace

      - name: Configure AWS credentials
        uses: Fooji/create-aws-profile-action@v1
        with:
          profile: sunteck
          region: us-east-1
          key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Bootstrap
        working-directory: ./_devops/db_sync
        run: make bootstrap files

      - name: qc-btms
        working-directory: ./_devops/db_sync
        run: ./sync_rds.py --skip-ask --env_target qc --app_name btms
         
      - name: Team Notify of Success
        uses: toko-bifrost/ms-teams-deploy-card@3.1.2
        with:
          github-token: ${{ github.token }}
          webhook-uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
          timezone: US/Eastern
          #github-token: ${{ github.token }}
          #ms-teams-webhook-uri: ${{ secrets.MS_DEVOPS_TEAMS_WEBHOOK_URI }}
          #notification-summary: "BTMS deployment to ${{ inputs.app_env }} (${{ github.actor }}): Test success"
          #notification-color: 33ff66
      - name: Team Notify of Failure
        if: ${{ failure() }}
        uses: toko-bifrost/ms-teams-deploy-card@3.1.2
        with:
          github-token: ${{ github.token }}
          webhook-uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
          timezone: US/Eastern
          #github-token: ${{ github.token }}
          #ms-teams-webhook-uri: ${{ secrets.MS_DEVOPS_TEAMS_WEBHOOK_URI }}
          #notification-summary: "BTMS deployment to ${{ inputs.app_env }} (${{ github.actor }}): Test failed:"
          #notification-color: ff0000
